// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPYC6t5iBSZ5i2HjDDjTW9PCn3wgILUHc',
    appId: '1:990557377111:web:1551c917982093ff860912',
    messagingSenderId: '990557377111',
    projectId: 'myapp-7f561',
    authDomain: 'myapp-7f561.firebaseapp.com',
    storageBucket: 'myapp-7f561.firebasestorage.app',
    measurementId: 'G-0V607ZMC9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa3PaA2mNy7TPlr5Z5qkm5GDTXwf-n_ZQ',
    appId: '1:990557377111:android:661e790347e300aa860912',
    messagingSenderId: '990557377111',
    projectId: 'myapp-7f561',
    storageBucket: 'myapp-7f561.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGGBYVs2dqVRoK_E_G5LTzfK4bRGmZf2E',
    appId: '1:990557377111:ios:d58941e85414576b860912',
    messagingSenderId: '990557377111',
    projectId: 'myapp-7f561',
    storageBucket: 'myapp-7f561.firebasestorage.app',
    iosClientId:
        '990557377111-gpmrhtdhv2uv27bleagceh6so9rvjotr.apps.googleusercontent.com',
    iosBundleId: 'com.example.skincareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGGBYVs2dqVRoK_E_G5LTzfK4bRGmZf2E',
    appId: '1:990557377111:ios:d58941e85414576b860912',
    messagingSenderId: '990557377111',
    projectId: 'myapp-7f561',
    storageBucket: 'myapp-7f561.firebasestorage.app',
    iosClientId:
        '990557377111-gpmrhtdhv2uv27bleagceh6so9rvjotr.apps.googleusercontent.com',
    iosBundleId: 'com.example.skincareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPYC6t5iBSZ5i2HjDDjTW9PCn3wgILUHc',
    appId: '1:990557377111:web:ba4b2e6e80b8e129860912',
    messagingSenderId: '990557377111',
    projectId: 'myapp-7f561',
    authDomain: 'myapp-7f561.firebaseapp.com',
    storageBucket: 'myapp-7f561.firebasestorage.app',
    measurementId: 'G-3BW8YRXD7S',
  );
}
